import { currentUser } from "@clerk/nextjs/server";
import { Mail, Calendar, ShieldCheck } from "lucide-react";
import { Topbar } from "@/components/dashboard/topbar";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";

export default async function ProfilePage() {
  const user = await currentUser();

  const fullName = [user?.firstName, user?.lastName].filter(Boolean).join(" ") || "MedAgent User";
  const email = user?.emailAddresses?.[0]?.emailAddress ?? "—";
  const joined = user?.createdAt
    ? new Date(user.createdAt).toLocaleDateString("en-US", { month: "long", year: "numeric" })
    : "—";
  const initials = fullName
    .split(" ")
    .map((n) => n[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();

  return (
    <>
      <Topbar title="Profile" />
      <main className="flex-1 space-y-6 p-4 sm:p-6 lg:p-8">
        <Card className="border-border/60 bg-card/60 backdrop-blur">
          <CardContent className="flex flex-col items-center gap-4 p-8 text-center sm:flex-row sm:text-left">
            <Avatar className="h-20 w-20">
              <AvatarImage src={user?.imageUrl} alt={fullName} />
              <AvatarFallback className="text-xl">{initials}</AvatarFallback>
            </Avatar>
            <div>
              <h2 className="font-display text-xl font-bold">{fullName}</h2>
              <p className="mt-1 flex items-center justify-center gap-1.5 text-sm text-muted-foreground sm:justify-start">
                <Mail className="h-3.5 w-3.5" /> {email}
              </p>
              <div className="mt-3 flex flex-wrap justify-center gap-2 sm:justify-start">
                <Badge variant="success" className="gap-1">
                  <ShieldCheck className="h-3 w-3" /> Verified account
                </Badge>
                <Badge variant="outline" className="gap-1">
                  <Calendar className="h-3 w-3" /> Joined {joined}
                </Badge>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="grid gap-6 md:grid-cols-2">
          <Card className="border-border/60 bg-card/60 backdrop-blur">
            <CardHeader>
              <CardTitle>Account activity</CardTitle>
              <CardDescription>Your engagement across all agents.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {[
                { label: "Total consultations", value: "23" },
                { label: "Reports analyzed", value: "5" },
                { label: "Medicines identified", value: "8" },
                { label: "Voice sessions", value: "6" },
              ].map((stat, i) => (
                <div key={stat.label}>
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground">{stat.label}</span>
                    <span className="font-semibold">{stat.value}</span>
                  </div>
                  {i < 3 && <Separator className="mt-4" />}
                </div>
              ))}
            </CardContent>
          </Card>

          <Card className="border-border/60 bg-card/60 backdrop-blur">
            <CardHeader>
              <CardTitle>Medical disclaimer</CardTitle>
              <CardDescription>Please read before relying on any agent.</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed text-muted-foreground">
                MedAgent AI provides general health information and triage
                guidance generated by an AI model. It is not a licensed
                medical professional, cannot diagnose conditions, and should
                never replace consultation with a qualified doctor,
                pharmacist, or emergency service. Always seek professional
                medical advice for any health concern, especially urgent ones.
              </p>
            </CardContent>
          </Card>
        </div>
      </main>
    </>
  );
}
